modLoader = "javafml"
loaderVersion = "[40,)"
license = "AGPL v3"
[[mods]]
modId = "drinkit"
version = "1.0.2"
displayName = "Drink It!"
credits = "Thanks for rinko1231's idea"
authors = "Tapio"
description = '''
'''